version: '3.8'

services:
  db-auth:
    image: mysql:8.0
    container_name: db_auth_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_auth
    ports:
      - "3306:3306"
    volumes:
      - auth_data:/var/lib/mysql

  db-catalog:
    image: mysql:8.0
    container_name: db_catalog_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_catalog
    ports:
      - "3307:3306"
    volumes:
      - catalog_data:/var/lib/mysql

  db-production:
    image: mysql:8.0
    container_name: db_production_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_production
    ports:
      - "3308:3306"
    volumes:
      - production_data:/var/lib/mysql

  db-quality:
    image: mysql:8.0
    container_name: db_quality_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_quality
    ports:
      - "3309:3306"
    volumes:
      - quality_data:/var/lib/mysql

volumes:
  auth_data:
  catalog_data:
  production_data:
  quality_data: